---
title: "Common Challenges Working With Data"
author: "Ward, A, Rivas, S., Shenasa, A."
format: 
  pdf: default
editor: visual
---

## The Burdens of Messy Data

Working with data can be frustrating. Collecting data is difficult and humans make mistakes meaning that often times the data we first begin to analyze and interpret can be full of flaws and mistakes. Programming languages aren't perfect either and need direction on how your data is formatted to be able to interpret it properly.

We have all experienced a time when messy data (either of our own doing or others) has nearly made us pull our hair out from frustration. This can be especially true when you're beginning to interact with a programming language for the first time. Our hope is to alleviate some of that stress and burden by giving some guidance on how to handle common data issues that can arise.

Here, we've narrowed down six of the more common challenges we have experienced while analyzing and visualizing data. We have broken down how these challenges may arise and given some suggestions and examples on how to proceed.

## Our Top Six Data Challenges

1.  ***Missing Data***

    In R, missing values in a data set are often represented by NA. This will either be from blank cells being filled in with NAs as the data frame is uploaded or if the uploaded data frame already contains NAs rather than blank cells. However, this can get messy for a number of reasons when NAs are mislabeled (i.e. N/A vs. N.A. vs. NA - which we deal with in our *Inconsistent Formatting* section), when you don't know how many missing values there are, or when they harm the visualization or interpretation of your data.

-   Checking data set for missing values

    If you have missing values in your data set, a good first step is simply to check for the presence of NAs. This will give an output of TRUE or FALSE based on the presence of missing values.

    ```{r}
    #| output: TRUE

    x <- c(8,12,NA,19,2,NA,99,4,78,1,32,NA)
    is.na(x)
    ```

-   Counting missing values

    If the amo

-   Excluding missing values- (na.omit na.rm)

-   Imputing NAs

2.  ***Inconsistent Formatting***
